apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: eyeball
      defaultBucket: detections
      tlsSkipVerify: true
    secureJsonData:
      token: eyeball-super-secret-token-change-in-production