"""
Configuration constants for the Eyeball application.
"""

# Detection settings
DEFAULT_DETECTION_FPS = 6.0
FRAME_SKIP_INTERVAL_BASE = 30  # Assuming ~30 FPS input stream

# Memory management
MEMORY_LEAK_THRESHOLD_MB = 2000
MEMORY_HIGH_USAGE_THRESHOLD_MB = 2400
MEMORY_CLEANUP_INTERVAL_FRAMES = 50
MEMORY_DEEP_CLEANUP_INTERVAL_FRAMES = 200
MEMORY_HISTORY_SIZE = 20
MEMORY_LEAK_SLOPE_THRESHOLD_MB_PER_MIN = 20.0

# Motion detection
MOTION_THRESHOLD_PIXELS = 2000
MOTION_PIXEL_PERCENTAGE_MULTIPLIER = 100
BACKGROUND_SUBTRACTOR_HISTORY = 100
BACKGROUND_SUBTRACTOR_VAR_THRESHOLD = 50

# Object tracking
TRACKING_POSITION_HISTORY_SIZE = 30
TRACKING_CLEANUP_TIME_SECONDS = 15
TRACKING_MAX_POSITIONS = 20
TRACKING_MIN_POSITIONS_FOR_LOGGING = 10
TRACKING_MIDPOINT_DISPLACEMENT_THRESHOLD = 50

# Queue settings
FRAME_QUEUE_MAX_SIZE = 24

# GUI settings
DASHBOARD_WIDTH = 1600
DASHBOARD_HEIGHT = 900
VIDEO_FRAME_HEIGHT = 450
METRICS_COLUMN_WIDTH = 534
VIDEO_COLUMN_WIDTH = 1066

# SRT connection
SRT_CONNECTION_TIMEOUT_MS = 5000000  # 5 seconds

# Logging
INFLUX_LOG_MAX_ENTRIES = 150

# Speed calculation
FEET_PER_MILE = 5280
SECONDS_PER_HOUR = 3600
